---
title: "Vitaspec_fruits"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Ubuntu}[
      Path = /usr/share/fonts/truetype/ubuntu/,
      Extension = .ttf,
      UprightFont = *-R,
      BoldFont = *-B,
      ItalicFont = *-RI,
      BoldItalicFont = *-BI
    ]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load & Save data
```{r eval=FALSE, include=FALSE}

library(nirsextra)
library(plyr)
source("vitaspec_load.R")

# d0="C:/Users/guest/Documents/Martin/VitaSPEC/"
# d0="/home/ecarnot/Documents/INRA/Projets/VitaSPEC/"
d0="C:/Users/U108-N806/Documents/STAGE_M2_ROSA_NIRS/VitaSPEC/"


# AG=read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Résultats VitaSpec Méso AG serie 1 (61 échantillons).csv"), sep=";", header=TRUE, dec=",")

AG <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.2.csv"), 
                 sep=";", 
                 header=TRUE, 
                 dec=",")
AG$ech <- sub("-.*", "", AG$code_nirs)
AG_new <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/AG_new.csv"),
                     sep = ",",
                     header = TRUE,
                     dec = ".")
AG_new$ech <- sub("-.*", "", AG_new$code_nirs)
AG <- join(AG, AG_new, by = "ech", type = "full")

carot <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.3.csv"), 
                 sep=";", 
                 header=TRUE, 
                 dec=",")[,-2]
carot$ech <- sub("-.*", "", carot$code_nirs)

tlip <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.4.csv"), 
                sep=";", 
                header=TRUE, 
                dec=",")
tlip$ech <- sub("-.*", "", tlip$code_nirs)
tlip_new <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Tlip_new.csv"), 
                sep=",", 
                header=TRUE, 
                dec=".")
tlip_new$ech <- sub("-.*", "", tlip_new$code_nirs)
tlip <- join(tlip, tlip_new, by = "ech", type = "full")

meso <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/V4_Vitaspec_cpx_meso_M1àM306_fm1_sd_me.csv"),
                   sep=";", 
                   header=TRUE, 
                   dec=",")

names(meso)[names(meso) == "TE1...MF."] <- "eau"

ref <- join_all(list(meso,AG, carot,tlip), 
                by = 'ech', 
                type = 'full')


# Load spectra
dirs <- basename(list.dirs(paste0(d0,"spectres/"), 
                           recursive = FALSE))

dirs_vita <- grep("_Vita", 
                  dirs, 
                  value = TRUE)  # Garder ceux qui contiennent "Vita"

dirs <- grep("HR", 
             dirs_vita, 
             value = TRUE, 
             invert = TRUE) # Enlever ceux qui contiennent "HR"

sp <- merge(vitaspec_load(paste0(d0,"spectres/"),
                          dirs[1]),
            vitaspec_load(paste0(d0,"spectres/"),
                          dirs[2]),
            by="spname",
            all=TRUE)

for (i in 3:(length(dirs))) {sp <- merge(sp,
                                        vitaspec_load(paste0(d0,"spectres/"),
                                                       dirs[i]),
                                         by="spname",
                                         all=TRUE)}

sp <- sp[-grep("Spectrum", sp$spname),]
sp$ech <- sub("-.*", "", sp$spname)
sp$rep <- as.numeric(substr(sp$spname,nchar(sp$spname)-4,
                            nchar(sp$spname)))


# Set sample state
sp$etat=NA

sp$etat[(!is.na(sp$x20240325_Vitaspec_Pobe[,1]) | !is.na(sp$x20250224_Vitaspec_Pobe[,1])) & !grepl("X",sp$spname)]="Meso_frais"

sp$etat[(!is.na(sp$x20240325_Vitaspec_Pobe[,1]) | !is.na(sp$x20250224_Vitaspec_Pobe[,1])) & grepl("X",sp$spname)]="Exo"

sp$etat[(!is.na(sp$x20240405_VitaSPEC_S_DIADE[,1]) | !is.na(sp$x20250313_Vitaspec_S_DIADE[,1]))]="Meso_Silica"

sp$etat[(!is.na(sp$x20250319_Vitaspec_Lyoph_DIADE[,1]) | !is.na(sp$x20250321_Vitaspec_Lyoph_DIADE[,1]))]="Meso_Lyoph"

sp=merge(sp,ref,by="ech",all.y=TRUE)

save(sp,file="vitaspec_fruit")
```

# Cross-Val
```{r echo=FALSE, warning=FALSE, results='asis'}
suppressPackageStartupMessages(library(rchemo))
suppressPackageStartupMessages(library(nirsextra))
library(data.table)
source("vitaspec_preCV.R")
source("list_pre.R")
load("vitaspec_fruit")
param=read.csv("Vitaspec_fruit_param.csv")
sp0=sp
outtxt=list()
fm_all=list()
id_model=list()
list_ag=c()

condition_spectr=c("Mesocarpe Frais - 24-25","Exocarpe Frais - 24-25","Mesocarpe Silicagel - 24-25","Mesocarpe Lyoph - 24-25")
for (k in 1) { #length(condition_spectr)) {
  sp=sp0
  # On selectionne les bons spectres selon la condition (Meso frais, Exo, ...)
  if (k==1) {
      sp$x=sp$x20240325_Vitaspec_Pobe
      iokPobe25=which(!is.na(sp$x20250224_Vitaspec_Pobe[,1]))
      sp$x[iokPobe25,] = sp$x20250224_Vitaspec_Pobe[iokPobe25,]
      sp=sp[!is.na(sp$x[,1]) & !grepl("X",sp$spname),]
      idparam="meso_frais"
  } else if (k==2) {
      cat("\n\n\\pagebreak\n")
      sp$x=sp$x20240325_Vitaspec_Pobe
      iokPobe25=which(!is.na(sp$x20250224_Vitaspec_Pobe[,1]))
      sp$x[iokPobe25,] = sp$x20250224_Vitaspec_Pobe[iokPobe25,]
      sp=sp[!is.na(sp$x[,1]) & grepl("X",sp$spname),]
      idparam="exo_frais"
  } else if (k==3) { 
      cat("\n\n\\pagebreak\n")
      sp$x=sp$x20240405_VitaSPEC_S_DIADE
      iokS25=which(!is.na(sp$x20250313_Vitaspec_S_DIADE[,1]))
      sp$x[iokS25,] = sp$x20250313_Vitaspec_S_DIADE[iokS25,]
      sp=sp[!is.na(sp$x[,1]),]
      idparam="meso_silica"
  } else if (k==4) {
      cat("\n\n\\pagebreak\n")
      sp$x=sp$x20250319_Vitaspec_Lyoph_DIADE
      iokL25=which(!is.na(sp$x20250321_Vitaspec_Lyoph_DIADE[,1]))
      sp$x[iokL25,] = sp$x20250321_Vitaspec_Lyoph_DIADE[iokL25,]
      sp=sp[!is.na(sp$x[,1]),]
      idparam="meso_lyoph"
  }
  cat(paste0("\\begin{center}\n\\fontsize{24}{16}\\selectfont\\underline{", condition_spectr[k], "}\n\\end{center}\n\\normalsize\n\\par\n"))

  ag=colnames(sp)[c(34,45:59)] 
  options(warn=-1)
 
  # En moyennant les rép
  dat=aggregate(sp,by=list(sp$ech), mean)
  dat$x=as.matrix(aggregate(sp$x, list(sp$ech), mean)[,-1])
  dat$ech=dat$Group.1; dat=dat[,-1] 
  if (nrow(dat)<100) {rdmsp=1:nrow(dat)} else {rdmsp=sample.int(nrow(dat),100)}
  plotsp(dat$x[rdmsp,])
  title(paste0(condition_spectr[k],"  spectres bruts"))
  
  for (i in 1:length(ag)) {
    ag1=ag[i]
    print(ag1)
    iout=which(is.na(dat[,colnames(dat)==ag1]))
    if (length(iout)>0) {datok=dat[-iout,]} else datok=dat

    vitaspec_preCV(datok$x,datok[,colnames(datok)==ag1],fun="plskern",list_pre,15, titl=condition_spectr[k])
    
    # Modèle Complet après avoir choisit les meilleurs pré+nLV
    #iokparam=which(grepl(idparam,param$Cal_data) & param$Propriete==ag1)
    # eval(parse(text = paste0("p = ", param[iokparam, ]$pre)), envir = .GlobalEnv)
    # fm_finale = plskern(pre(datok$x,p), datok[,colnames(datok)==ag1],nlv=param[iokparam,]$nvl)
    # fm_all=append(fm_all,list(fm_finale))
    # id_model=rbind(id_model,c(ag1,idparam))
  }
}
# save(fm_all,id_model,file="Vitaspec_fruit_models")
```

# Comparaison des spectres selon conditions
```{r echo=FALSE}
library(rchemo)
load("vitaspec_fruit")

condition_spectr=c("Mesocarpe Frais - 24-25","Exocarpe Frais - 24-25","Mesocarpe Silicagel - 24-25","Mesocarpe Lyoph - 24-25")
cols_x <- grep("^x", names(sp), value = TRUE)
mat_concat <- do.call(rbind, sp[cols_x])
etat=rep(sp$etat,10)
spcmp=mat_concat[!is.na(mat_concat[,1]),]
etat=etat[!is.na(mat_concat[,1])]
# colnames(spcmp)=colnames(sp$x20240325_Vitaspec_Pobe)
spcmpm=aggregate(spcmp, list(etat), mean)
etatm=spcmpm$Group.1
spcmpm=as.matrix(spcmpm[,-1])

col <- hcl.colors(n = nrow(spcmpm))
plotsp(spcmpm,col=col)
legend(x="topright",legend=etatm, col = col,lty=1)

```

# Cal 2024, applied on 2025
```{r eval=FALSE, include=FALSE}

```



# Calibration with dryed mesocarp - Compare AGAP and DIADE spectrometer
```{r eval=FALSE, warning=FALSE, include=FALSE}
d="/home/ecarnot/Documents/INRA/Projets/VitaSPEC/"
sp=sp2df(asd_read_dir(paste0(d,"spectres/20240405_VitaSPEC_S_AGAP/")))
sp$ech=sub("-[^-]*$", "", rownames(sp))
ref=read.table(paste0(d,"analyses_ref/Données_pour_NIRS_TEmeso.csv"), sep=";",header=TRUE, dec = ",")
ref$ech=paste0(ref$Identifiant,"-",ref$Code.arbre)
colnames(ref)[colnames(ref) == "TE1...MF."] = "Eau"
sp=merge(sp, ref,by="ech")
spm=aggregate(sp,by=list(sp$ech), mean)
spm$x=as.matrix(aggregate(sp$x, list(sp$ech), mean)[,-1])
spm$ech=spm$Group.1; spm=spm[,-1]
vitaspec_preCV(spm$x,spm$Eau,list_pre,10, titl="Teneur en eau. Pts de mesures moy. par fruit. Meso séché - AGAP") 

sp=sp2df(asd_read_dir(paste0(d,"spectres/20240405_VitaSPEC_S_DIADE/")))
sp$ech=sub("-[^-]*$", "", rownames(sp))
sp=merge(sp, ref,by="ech")
spm=aggregate(sp,by=list(sp$ech), mean)
spm$x=as.matrix(aggregate(sp$x, list(sp$ech), mean)[,-1])
spm$ech=spm$Group.1; spm=spm[,-1]
vitaspec_preCV(spm$x,spm$Eau,list_pre,10, titl="Teneur en eau. Pts de mesures moy. par fruit.  Meso séché - DIADE") 
```

# Explore 2 years on fresh fruits
```{r echo=FALSE, warning=FALSE}
library(rchemo)
library(nirsextra)
# d="C:/Users/guest/Documents/Martin/VitaSPEC/"
d="/home/ecarnot/Documents/INRA/Projets/VitaSPEC/"
sp24=sp2df(asd_read_dir(paste0(d,"spectres/20240325_Vitaspec_Pobe/")))
sp24$annee=24
sp25=sp2df(asd_read_dir(paste0(d,"spectres/20250224_Vitaspec_Pobe/")))
sp25$annee=25
sp=rbind(sp24,sp25)
# Excude exocarp spectra
sp=sp[!grepl("FX",rownames(sp)),]

sp$ech=sub("-[^-]*$", "", rownames(sp))
# Average spectra
spm=aggregate(sp,by=list(sp$ech), mean)
spm$x=as.matrix(aggregate(sp$x, list(sp$ech), mean)[,-1])
spm$ech=spm$Group.1; spm=spm[,-1]
# spm=sp

p=rbind(list('adj',''),list('snv',''))
spm$xp=pre(spm$x,p)
loess_fit <- apply(spm$xp, 1, function(s) loess(s ~ as.integer(colnames(spm$xp)), span = 0.05))
spm$xp2 <- I(t(sapply(loess_fit, function(t) t$fitted)))

col=rep("red",nrow(spm))
col[spm$annee==24]="black"
plotsp(spm$x,col=col)

fm <- pcaeigen(spm$xp2, nlv = 10)
plotxy(fm$T[, c(1,2)], group = spm$annee)

#plot from VS
# library(RColorBrewer)
# couleur <- brewer.pal(n = length(levels(as.factor(nirs.list.ade4$raw$info$Bloc))),
#                       name = "Set1")
# for (i in (1:length(pca.nirs))){
#   s.class(dfxy = pca.nirs[[i]]$li,
#           fac = as.factor(nirs.list.ade4[[i]]$info$Bloc), xax = 1, yax = 2,
#           clabel = 0.7, col = couleur, sub = names(pca.nirs)[i], csub=2, possub="topleft")

```










# Prédiction de nouveaux échantillons
```{r eval=FALSE, include=FALSE}
library(nirsextra)
library(rchemo)
library(openxlsx)
# load('vitaspec_fruit')
load("Vitaspec_fruit_models")
param=read.csv("Vitaspec_fruit_param.csv")

f="/home/ecarnot/Documents/INRA/Projets/VitaSPEC/spectres/20240325_Vitaspec_Pobe/"
spnew=rbind(asd_read_dir(f), asd_read_dir("/home/ecarnot/Documents/INRA/Projets/VitaSPEC/spectres/20250224_Vitaspec_Pobe/"))
spnew=spnew[!grepl("X",rownames(spnew)),]
cond="meso_frais"
param=param[grepl(cond,param$Cal_data),]

# PCA
# fm=pcaeigen(sp$x, nlv = 5)
# Ttrain=fm$T
# Ttest <- transform(fm, spnew)
# T <- rbind(Ttrain, Ttest)
# group <- c(rep("Training", nrow(sp)), rep("Test", nrow(spnew)))
# i=1
# plotxy(T[, i:(i+1)], group = group, pch = 16, zeroes = TRUE, cex = 1.3, main = "scores")

# Prédiction
pred=data.frame(spectrum=rownames(spnew))
nag=dim(param)[1]

for (i in 1:nag) {
eval(parse(text = paste0("p = ", param[i,]$pre)))
spnx=pre(spnew,p)
imodel=which(grepl(cond,id_model[,2]) & grepl(param[i,]$Propriete,id_model[,1]))
pred=cbind(pred,predict(fm_all[[imodel]], spnx)$pred) # les modèles sont dans le meme ordre que les ag, car construits avec "param"
}
colnames(pred)[2:2:(nag+1)]=param$Propriete

# Stats par échantillon
library(dplyr)
library(tidyr)
pred$ech=substr(pred$spectrum,1,nchar(pred$spectrum)-5)
group_col <- "ech"

pred_moy <- select(pred,-spectrum) %>%
  group_by(ech) %>%
  summarise(across(where(is.numeric), mean), .groups = "drop")

pred_stats <- select(pred,-spectrum) %>%
  pivot_longer(cols = -all_of(group_col), names_to = "Variable", values_to = "Valeur") %>%
  group_by(across(all_of(group_col)), Variable) %>%
  reframe(
    Stat = c("mean", "sd", "min", "max"),
    Valeur = c(mean(Valeur), sd(Valeur), min(Valeur), max(Valeur))
  ) %>%
  pivot_wider(names_from = Stat, values_from = Valeur)

library(openxlsx)
titre="Pobe_24-25_NIRS_Meso_Frais"
write.xlsx(pred, file = paste0("predictions/",titre,"_pred.xlsx"))
write.xlsx(pred_moy, file = paste0("predictions/",titre,"_pred_moy.xlsx"))
write.xlsx(pred_stats, file = paste0("predictions/",titre,"_pred_stats.xlsx"))

# # Check Results independantly
# load('vitaspec_fruit')
# tab1=sp[!duplicated(sp$ech), colnames(sp) %in% unique(param$Propriete)]
# tab2=read.xlsx("/home/ecarnot/Documents/INRA/Projets/VitaSPEC/vitaspec_R/predictions/Pobe_24-25_NIRS_Meso_Frais_pred_moy.xlsx")[,-1]
# library(ggplot2)
# 
# for (col in names(tab1)) {
#   df <- data.frame(
#     x = tab2[[col]],
#     y = tab1[[col]]
#   )
#   r2 <- summary(lm(y ~ x, df))$r.squared
# 
#   print(
#     ggplot(df, aes(x, y)) +
#       geom_point() +
#       geom_smooth(method = "lm", se = FALSE) +
#       annotate(
#         "text",
#         x = min(df$x, na.rm = TRUE),
#         y = max(df$y, na.rm = TRUE),
#         label = paste0("R² = ", round(r2, 3)),
#         hjust = 0
#       ) +
#       labs(title = col)
#   )
# }

```


# Outlier detection
```{r}
library(nirsextra)
library(openxlsx)
library("PerformanceAnalytics")
source("vitaspec_load.R")
ssech=1
d0="/home/ecarnot/Documents/INRA/Projets/VitaSPEC/"
# Load spectra
dirs=basename(list.dirs(paste0(d0,"spectres/"), recursive = FALSE))
dirs_frais <- grep("_Pob", dirs, value = TRUE)
sp24=vitaspec_load(paste0(d0,"spectres/"),dirs_frais[1])
sp24=sp24[!grepl("X", rownames(sp24)),]
colnames(sp24)[1]="x"
sp24=sp24[sample(nrow(sp24),nrow(sp24)/ssech),]
sp25=vitaspec_load(paste0(d0,"spectres/"),dirs_frais[2])
sp25=sp25[!grepl("X", rownames(sp25)),]
colnames(sp25)[1]="x"
sp25=sp25[sample(nrow(sp25),nrow(sp25)/ssech),]

sp=rbind(sp24,sp25)
sp$annee=2025
sp$annee[1:nrow(sp24)]=2024
# sp$tissue="meso"
# sp$tissue[grep("X", rownames(sp))]="exo"
sp$xp=snv(sp$x)

i24=1:nrow(sp)
fm <- pcasvd(sp$xp[i24,], nlv = 6)
scord=scordis(fm,sp$xp)
plot(scord$res$dstand)

# Voir s'il y a un lien entre Maha distance et mauvaise prediction (surtout <0)
predbioch=read.xlsx(paste0(d0,"vitaspec_R/predictions/Pobe_24-25_NIRS_Meso_Frais_pred.xlsx"))
sc=data.frame(scord$res$dstand)
sc$spectrum=rownames(sp)
scbioch=merge(predbioch,sc,by = "spectrum")
chart.Correlation(scbioch[,-c(1,18)])

# dt=data.frame(fm$Tr)
# p1 = ggplot(data = dt, aes(x = comp1, y = comp2, color=sp1$JafterL, shape = sp1$ech)) + geom_point(size=3) + labs(title = "Effet de la Lyophilisation - ACP globale ",x = "comp1", y = "comp2") + scale_color_manual(values = c("red","blue","black"))
# plot(p1)

iout=which(scord$res$dstand>1)
plotsp(sp)

fm <- plsrda(sp$xp[i24,], sp$tissue[i24], nlv = 8)
pred = predict(fm, sp$xp[-i24,])
err(pred$pred, sp$tissue[-i24])
```

