---
title: "ROSA_vitaSPEC_fruits"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center",
                      fig.width = 6, fig.height = 4)

library(ggplot2)
library(dplyr)
library(writexl)
library(nirsextra)
library(tidyverse)
library(rchemo)
library(stringr)
library(purrr)
library(pls)


d0 <- "C:/Users/U108-N806/Documents/STAGE_M2_ROSA_NIRS/VitaSPEC/"
source(paste0(d0,"vitaspec_R/vitaspec_load.R"))
source(paste0(d0,"vitaspec_R/vitaspec_preCV_lwplsr.R"))
source(paste0(d0,"vitaspec_R/list_pre.R"))
source(paste0(d0,"vitaspec_R/Rosa_vitaSPEC/compile_spectres.R"))
load(paste0(d0,"vitaspec_R/vitaspec_fruit"))
param=read.csv(paste0(d0,"vitaspec_R/Vitaspec_fruit_param.csv"))


theme_set(theme_minimal())
```

# Load & Save data

## Yvalue

```{r, echo=FALSE}

### AG
AG_new <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/AG_new.csv"),
                     sep = ",",
                     header = TRUE,
                     dec = ".") %>% 
  mutate(ech = sub("-.*", "", code_nirs))

AG <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.2.csv"), 
                 sep=";", 
                 header=TRUE, 
                 dec=",") %>%
  mutate(ech = sub("-.*", "", code_nirs)) %>% 
  bind_rows(AG_new) %>% 
  select(-c(1,2))

### carotène
carot <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.3.csv"),
                    sep=";", 
                    header=TRUE, 
                    dec=",") %>%
  mutate(ech = sub("-.*", "", code_nirs)) %>% 
  select(-c(1,2))

### lip totaux
tlip_new <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Tlip_new.csv"), 
                sep=",", 
                header=TRUE, 
                dec=".") %>% 
  mutate(ech = sub("-.*", "", code_nirs))

tlip <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.4.csv"), 
                   sep=";", 
                   header=TRUE, 
                   dec=",") %>%
  mutate(ech = sub("-.*", "", code_nirs)) %>% 
  select(-c(1,3))

### eau
meso <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/V4_Vitaspec_cpx_meso_M1àM306_fm1_sd_me.csv"), 
                   sep=";", 
                   header=TRUE, 
                   dec=",") %>%
  rename(eau = `TE1...MF.`)
eau <- meso %>% 
  select(ech,eau)

### merge 
Yvalue <- eau %>%
  full_join(AG, by = "ech") %>%
  full_join(tlip, by = "ech") %>% 
  full_join(carot, by = "ech")

### export

write.csv(Yvalue, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques.csv"),row.names = FALSE)

write_xlsx(Yvalue, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques.xlsx"))
```

## Xvalue

```{r, echo=FALSE}
### Load spectra
dirs <- list.dirs(paste0(d0, "spectres/"), recursive = FALSE) %>%
  basename() %>%                     # recup le nom des dossiers
  as_tibble() %>%                    # tibble pour dyplr
  filter(grepl("_Vita", value)) %>%  
  filter(!grepl("HR", value)) %>%    
  pull(value)                        # retours sous forme de liste 

### merge de tous les campagnes de spectres
Xvalue <- merge(vitaspec_load(paste0(d0,"spectres/"),
                       dirs[1]),
                vitaspec_load(paste0(d0,"spectres/"),
                       dirs[2]),
                by="spname",
                all=TRUE)

for (i in 3:(length(dirs))) { Xvalue <- merge(Xvalue,
                                              vitaspec_load(paste0(d0,"spectres/"),
                                                            dirs[i]),
                                              by="spname",
                                              all=TRUE)}

### clean des spectres sans nom (erreur manip)
Xvalue <- Xvalue %>%
  filter(!str_detect(spname, "Spectrum")) %>% 
  mutate(
    ech = sub("-.*", "", spname),
    rep = as.numeric(substr(spname, 
                            nchar(spname)-4, 
                            nchar(spname)
                            )))
  
### ajout colonne "état"
Xvalue <- Xvalue %>%
  mutate(etat = case_when(
    # exo = Pobe et contient X
    (!is.na(x20240325_Vitaspec_Pobe[,1]) | !is.na(x20250224_Vitaspec_Pobe[,1])) & grepl("X", spname) ~ "Exo",

    # meso_frais = Pobe présentes et ne contient pas X
    (!is.na(x20240325_Vitaspec_Pobe[,1]) | !is.na(x20250224_Vitaspec_Pobe[,1])) & !grepl("X", spname) ~ "Meso_frais",

    # Mso_silica = 
    (!is.na(x20240405_VitaSPEC_S_DIADE[,1]) | !is.na(x20250313_Vitaspec_S_DIADE[,1])) ~ "Meso_Silica",

    # meso_Lyoph = 
    (!is.na(x20250319_Vitaspec_Lyoph_DIADE[,1]) | !is.na(x20250321_Vitaspec_Lyoph_DIADE[,1])) ~ "Meso_Lyoph",

    # si aucune condition 
    TRUE ~ NA_character_))

Xvalue <- Xvalue %>% 
  rename_with(~ str_remove_all(.x, "(?i)_Vitaspec"))
```


# Cross Validation

## Prep data 
```{r, echo=FALSE, warning=FALSE, results='asis'}
### spectres

Meso_frais_matrix <- compile_spectres_matrix(Xvalue,c("x20240325_Pobe","x20250224_Pobe"),"sans_X")
# Meso_frais_df <- compile_spectres_df(Xvalue,c("x20240325_Pobe","x20250224_Pobe"),"sans_X")


Exo_frais_matrix <- compile_spectres_matrix(Xvalue,c("x20240325_Pobe","x20250224_Pobe"),"avec_X")
# Exo_frais_df <- compile_spectres_df(Xvalue,c("x20240325_Pobe","x20250224_Pobe"),"avec_X")
  

Meso_sec_DIADE_matrix <- compile_spectres_matrix(Xvalue,c("x20240405_S_DIADE","x20250313_S_DIADE"))
# Meso_sec_DIADE_df <- compile_spectres_df(Xvalue,c("x20240405_S_DIADE","x20250313_S_DIADE"))
Meso_sec_AGAP_matrix <- compile_spectres_matrix(Xvalue,c("x20240405_S_AGAP","x20250313_S_AGAP"))
# Meso_sec_AGAP_df <- compile_spectres_df(Xvalue,c("x20240405_S_AGAP","x20250313_S_AGAP"))
Meso_sec_TOT_matrix <- compile_spectres_matrix(Xvalue,c("x20240405_S_DIADE","x20250313_S_DIADE","x20240405_S_AGAP","x20250313_S_AGAP"))
# Meso_sec_TOT_df <- compile_spectres_df(Xvalue,c("x20240405_S_DIADE","x20250313_S_DIADE","x20240405_S_AGAP","x20250313_S_AGAP"))

  
Meso_lyoph_DIADE_matrix <- compile_spectres_matrix(Xvalue,c("x20250319_Lyoph_DIADE","x20250321_Lyoph_DIADE"))
# Meso_lyoph_DIADE_df <- compile_spectres_df(Xvalue,c("x20250319_Lyoph_DIADE","x20250321_Lyoph_DIADE"))
Meso_lyoph_AGAP_matrix <- compile_spectres_matrix(Xvalue,c("x20250319_Lyoph_AGAP","x20250321_Lyoph_AGAP"))
# Meso_lyoph_AGAP_df <- compile_spectres_df(Xvalue,c("x20250319_Lyoph_AGAP","x20250321_Lyoph_AGAP"))
Meso_lyoph_TOT_matrix <- compile_spectres_matrix(Xvalue,c("x20250319_Lyoph_DIADE","x20250321_Lyoph_DIADE","x20250319_Lyoph_AGAP","x20250321_Lyoph_AGAP"))
# Meso_lyoph_TOT_df <- compile_spectres_df(Xvalue,c("x20250319_Lyoph_DIADE","x20250321_Lyoph_DIADE","x20250319_Lyoph_AGAP","x20250321_Lyoph_AGAP"))


mean_spectres <- function(data){
  data %>%
  group_by(ech) %>%
  summarise(
    x = matrix(colMeans(x, na.rm = TRUE), nrow = 1),
    .groups = "drop"
  )}

mean_Meso_frais_matrix <- mean_spectres(Meso_frais_matrix)


### chimie

ag <- Yvalue %>%
  select(2:17) %>%
  colnames()

join <- function(data){
  data %>% 
    left_join(Yvalue, by = "ech")
}

dat <- join(mean_Meso_frais_matrix)
```

## CV
```{r, echo=FALSE, warning=FALSE, results='asis'}
set.seed(123)

dat_clean <- dat[!is.na(dat$eau) & complete.cases(dat$x), ]
mod <- plsr(eau~x,data=dat_clean,ncomp=50,scale=TRUE,validation="CV",segments=10)
fitted(mod)
RMSEP(mod)


n <- nrow(dat_clean)
cvpred <- rep(0,n)

segs <- cvsegments(n,10)
cvpred <- rep(0,n)

for (k in 1:10){
  cvmod = plsr(eau~x, data = dat_clean[-segs[[k]],], ncomp = 50, scale = TRUE, validation = "CV", segments = 10)
  bestncomp = selectNcomp(cvmod,method = "onesigma")
  cvpred[segs[[k]]] = predict(cvmod, newdata = dat_clean[segs[[k]],])[,,bestncomp]
  print(bestncomp)
}
  
PRESS.pls <- sum((dat_clean$eau-cvpred)^2) ; PRESS.pls
sqrt(PRESS.pls/306)

graphics.off()
print(selectNcomp(mod,method = "onesigma",plot = TRUE))


R2_cv <- cor(dat_clean$eau, cvpred)^2

library(ggplot2)


df_plot <- data.frame(
  Observe = dat_clean$eau,
  Predite = cvpred
)
graphics.off()
p <- ggplot(df_plot, aes(x = Observe, y = Predite)) +
  geom_point(shape = 1, color = "black", size = 2.5) + 
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed", linewidth = 1) +
  geom_smooth(method = "lm", color = "blue", se = FALSE, linewidth = 1) +
  annotate("text", x = -Inf, y = Inf, 
           label = paste0("R^2 == ", round(R2_cv, 3)), 
           parse = TRUE, hjust = -0.2, vjust = 1.5, size = 5, color = "black") +
  labs(title = "PLSR - Eau",
       x = "Teneur mesurée",
       y = "Teneur prédite par SPIR") +
  theme_bw() + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"), # Centre le titre
    axis.title = element_text(face = "bold"))

print(p)
ggsave(filename = "PLS_eau_performance.png", 
       plot = p, 
       width = 8,        
       height = 6,       
       dpi = 300,        
       bg = "white")












# fm_all=list()
# id_model=list()
# idparam <- "meso_frais"
# 
# ag %>% 
#   walk(function(ag1) {
#     print(ag1)
#     datok <- dat %>% 
#       filter(!is.na(.data[[ag1]]))
#   
#     y_vals <- as.numeric(datok[[ag1]])
#     x_mat  <- as.matrix(datok$x)
# 
#     try({
#       vitaspec_preCV(
#         x = x_mat, 
#         y = y_vals, 
#         fun = "lwplsr", 
#         list_pre = list_pre, 
#         ncomp = 15, 
#         titl = "Meso_frais",
#         y_name = ag1
#       )
#     })
#   })
```

# Calibration finale
```{r, include=FALSE, echo=FALSE, warning=FALSE, results='asis'}
fm_all=list()
id_model=list()
idparam <- "meso_frais"

ag %>% 
  walk(function(ag1) {
    print(ag1)
    datok <- dat %>% 
      filter(!is.na(.data[[ag1]]))
  
    y_vals <- as.numeric(datok[[ag1]])
    x_mat  <- as.matrix(datok$x)

    try({
      vitaspec_preCV(
        x = x_mat, 
        y = y_vals, 
        fun = "lwplsr", 
        list_pre = list_pre, 
        ncomp = 15, 
        titl = "Meso_frais_lwplsr",
        y_name = ag1
      )
    })
    current_param <- param %>%
      filter(str_detect(Cal_data, idparam),
             Propriete == ag1)

    if (nrow(current_param) > 0) {
      p <- eval(parse(text = current_param$pre))
      n_lv <- current_param$nvl

      fm_finale <- plskern(
        pre(x_mat, p),
        y_vals,
        nlv = n_lv
        )
      fm_all <<- append(fm_all, list(fm_finale))
      id_model <<- id_model %>%
        bind_rows(tibble(Propriete = ag1,
                         Condition = idparam,
                         Methode = "lwplsr"))
    }
  })

save(fm_all, id_model, file = paste0(d0, "vitaspec_R/Vitaspec_fruit_models_lwplsr_2"))
```





















































