---
title: "ROSA_vitaSPEC_fruits"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center",
                      fig.width = 6, fig.height = 4)

library(ggplot2)
library(dplyr)
library(writexl)
library(openxlsx)
library(nirsextra)
library(tidyverse)
library(rchemo)
library(stringr)
library(purrr)
library(stringr)
library(ggpmisc)
library(pls)
library(tidymodels)
library(future)
library(furrr)
library(future.callr)



d0 <- "C:/Users/U108-N806/Documents/STAGE_M2_ROSA_NIRS/VitaSPEC/"
source(paste0(d0,"vitaspec_R/vitaspec_load.R"))
source(paste0(d0,"vitaspec_R/vitaspec_preCV.R"))
source(paste0(d0,"vitaspec_R/Rosa_vitaSPEC/compile_spectres.R"))
load(paste0(d0,"vitaspec_R/vitaspec_fruit"))

```

# Load & Save data

## Yvalue

```{r, echo=FALSE}
#FRUIT
### AG
AG_new <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/AG_new.csv"),
                     sep = ",",
                     header = TRUE,
                     dec = ".") %>% 
  mutate(ech = sub("-.*", "", code_nirs))
AG <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.2.csv"), 
                 sep=";", 
                 header=TRUE, 
                 dec=",") %>%
  mutate(ech = sub("-.*", "", code_nirs)) %>% 
  bind_rows(AG_new) %>% 
  select(-c(1,2))

### carotène
# carot <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.3.csv"),
#                     sep=";", 
#                     header=TRUE, 
#                     dec=",") %>%
#   mutate(ech = sub("-.*", "", code_nirs)) %>% 
#   select(-c(1,2))
carot <- read.xlsx(paste0(d0,"analyses_ref/fruits/méso-carot-sets_1-3=51_éch_Amel+92_Antoine_v2.xlsx")) %>%
  mutate(ech = sub("-.*", "", code_nirs),
         trans.alpha.carotene = `trans-alpha-carotène`,
         trans.beta.carotene = `trans-beta-carotène`,
         total.trans.carotene.natif = trans.alpha.carotene + trans.beta.carotene,
         ratio.alpha.beta = trans.alpha.carotene / trans.beta.carotene,
         ratio.alpha.natif = trans.alpha.carotene / total.trans.carotene.natif,
         ratio.beta.natif = trans.beta.carotene / total.trans.carotene.natif,
         X13.cis.beta.carotene = `13.cis-beta-carotène`,
         X9.cis.beta.carotene = `9.cis-beta-carotène`,
         total.beta.carotene = `total.beta-carotènes`,
         total.carotene = `total.carotènes`) %>% 
  select(-c(1:8))

### lip totaux
# tlip_new <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Tlip_new.csv"), 
#                 sep=",", 
#                 header=TRUE, 
#                 dec=".") %>% 
#   mutate(ech = sub("-.*", "", code_nirs))
# tlip <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.4.csv"), 
#                    sep=";", 
#                    header=TRUE, 
#                    dec=",") %>%
#   mutate(ech = sub("-.*", "", code_nirs)) %>% 
#   select(-c(1,3))

tlip <- read.xlsx(paste0(d0,"analyses_ref/fruits/méso-lip%MS-sets1-3=49échAmel+96Antoine.xlsx")) %>%
  mutate(ech = sub("-.*", "", code_nirs)) %>% 
  select(-c(1,3)) %>% 
  dplyr::rename( tlip.MS = `tlip%MS`)
  
  
### eau
meso <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/V4_Vitaspec_cpx_meso_M1àM306_fm1_sd_me.csv"), 
                   sep=";", 
                   header=TRUE, 
                   dec=",") %>% 
  dplyr::rename(eau = `TE1...MF.`)
eau <- meso %>% 
  select(ech,eau)

### merge 
Yvalue <- eau %>%
  full_join(AG, by = "ech") %>%
  full_join(tlip, by = "ech") %>% 
  full_join(carot, by = "ech")

### export
# write.csv(Yvalue, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques_new_FRUIT.csv"),row.names = FALSE)
# write_xlsx(Yvalue, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques_new_FRUIT.xlsx"))



#HUILE
### AG
AG_HR <- read.xlsx(paste0(d0,"analyses_ref/huile_rouge/Partie_1.2.xlsx")) %>% 
  mutate(ech = as.character(str_extract(ID, "(?<=#)[^-]+")),
         C14.0 = `C14:0`,
         C16.0 = `C16:0`,
         C18.0 = `C18:0`,
         C18.1n9 = `C18:1n9`,
         C18.2 = `C18:2`) %>% 
  select(-c(1:6))

###carotene
carot_HR <- read.xlsx(paste0(d0,"analyses_ref/huile_rouge/HR-carot-sets_1_à_3-115_ech_Amel+51_Marcel_v2.xlsx")) %>% 
  mutate(ech = as.character(str_extract(`#`, "(?<=#)[^-]+")),
         trans.alpha.carotene = `trans-alpha-carotène`,
         trans.beta.carotene = `trans-beta-carotène`,
         X13.cis.beta.carotene = `13.cis-beta-carotène`,
         X9.cis.beta.carotene = `9.cis-beta-carotène`,
         total.beta.carotene = `total.beta-carotènes`,
         total.carotene = total.carotènes,
         lycopene = `Lycopène`) %>% 
  select(-c(1:9))

###AGL
AGL_HR <- read.xlsx(paste0(d0,"analyses_ref/huile_rouge/Partie_1.4.xlsx")) %>% 
  mutate(ech = as.character(`#`),
         FFA = `FFA(%)`) %>% 
  select(-c(1:3))

###TOCO
TOCO_HR <- read.xlsx(paste0(d0,"analyses_ref/huile_rouge/HR-toco-sets_1_à_3-114_ech_Amel+50_Marcel.xlsx")) %>% 
  mutate(ech = as.character(str_extract(`#`, "(?<=#)[^-]+")),
         total.toco = TOTAL,
         total.T3 = TOTAL.T3) %>% 
  select(-c(1:3,8:9))

### merge 
Yvalue_HR <- carot_HR %>%
  full_join(AG_HR, by = "ech") %>%
  full_join(AGL_HR, by = "ech") %>% 
  full_join(TOCO_HR, by = "ech") %>% 
  relocate(ech,`C14.0`,`C16.0`,`C18.0`,`C18.1n9`,`C18.2`,`FFA`,trans.alpha.carotene,trans.beta.carotene,X13.cis.beta.carotene,X9.cis.beta.carotene,total.beta.carotene,total.carotene,lycopene,aT,aT3,gT3,dT3,total.T3,total.toco)

### export
# wr ite.csv(Yvalue_HR, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques_new_HR.csv"),row.names = FALSE)
# write_xlsx(Yvalue_HR, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques_new_HR.xlsx"))

```

## Xvalue

```{r, echo=FALSE}
# FRUITS
### Load spectra
dirs2024 <- list.dirs(paste0(d0, "spectres/"), recursive = FALSE) %>%
  basename() %>%                     # recup le nom des dossiers
  as_tibble() %>%                    # tibble pour dyplr
  filter(grepl("_Vita", value)) %>%  
  filter(!grepl("HR", value)) %>% 
  filter(grepl("2024",value)) %>% 
  pull(value)                        # retours sous forme de liste

dirs2025 <- list.dirs(paste0(d0,"spectres/"), recursive = FALSE) %>% 
  basename() %>%                     # recup le nom des dossiers
  as_tibble() %>%                    # tibble pour dyplr
  filter(grepl("_Vita", value)) %>%
  filter(!grepl("HR", value)) %>%
  filter(grepl("2025",value)) %>% 
  pull(value) 

dirs2026 <- list.dirs(paste0(d0,"spectres/"), recursive = FALSE) %>% 
  basename() %>%                     # recup le nom des dossiers
  as_tibble() %>%                    # tibble pour dyplr
  filter(grepl("_Vita", value)) %>%
  filter(!grepl("HR", value)) %>%
  filter(grepl("2026",value)) %>% 
  pull(value) 

dirs2026_vrai <- dirs2026[-c(5,7:9,15:16)]
dirs2026_test <- dirs2026[-c(1:4,6,10:16)]

### merge de tous les campagnes de spectres
Xvalue2024_fruit <- map_dfr(dirs2024, function(dossier) {
  data <- vitaspec_load(paste0(d0, "spectres/"), dossier)
  data$campagne <- 2024
  data$source <- case_when(
    str_detect(dossier, "AGAP") ~ "AGAP",
    str_detect(dossier, "DIADE") ~ "DIADE",
    str_detect(dossier, "Pobe") ~ "AGAP",
    TRUE ~ NA_character_)
  data$etat <- case_when(
    str_detect(dossier, "Pobe") & str_detect(data$spname, "X") ~ "Exo",
    str_detect(dossier, "Pobe") & !str_detect(data$spname, "X") ~ "Meso_frais",
    str_detect(dossier, "S_DIADE|S_AGAP") ~ "Meso_Silica",
    TRUE ~ NA_character_)
  return(data)
})
Xvalue2025_fruit <- map_dfr(dirs2025, function(dossier) {
  data <- vitaspec_load(paste0(d0, "spectres/"), dossier)
  data$campagne <- 2025
  data$source <- case_when(
    str_detect(dossier, "AGAP") ~ "AGAP",
    str_detect(dossier, "DIADE") ~ "DIADE",
    str_detect(dossier, "Pobe") ~ "AGAP",
    TRUE ~ NA_character_)
  data$etat <- case_when(
    str_detect(dossier, "Pobe") & str_detect(data$spname, "X") ~ "Exo",
    str_detect(dossier, "Pobe") & !str_detect(data$spname, "X") ~ "Meso_frais",
    str_detect(dossier, "S_DIADE|S_AGAP") ~ "Meso_Silica",
    str_detect(dossier, "Lyoph") ~ "Meso_Lyoph",
    TRUE ~ NA_character_)
  return(data)
})
Xvalue2026_fruit <- map_dfr(dirs2026_vrai, function(dossier) {
  data <- vitaspec_load(paste0(d0, "spectres/"), dossier)
  data$campagne <- 2026
  data$source <- case_when(
    str_detect(dossier, "AGAP") ~ "AGAP",
    str_detect(dossier, "DIADE") ~ "DIADE",
    TRUE ~ NA_character_)
  data$etat <- case_when(
    str_detect(dossier, "Pobe") & str_detect(data$spname, "X") ~ "Exo",
    str_detect(dossier, "Pobe") & !str_detect(data$spname, "X") ~ "Meso_frais",
    str_detect(dossier, "S_DIADE|S_AGAP") ~ "Meso_Silica",
    TRUE ~ NA_character_)
  return(data)
})
Xvalue2026_fruit_spe <- map_dfr(dirs2026_test, function(dossier) {
  data <- vitaspec_load(paste0(d0, "spectres/"), dossier)
  data$campagne <- 2026
  data$source <- case_when(
    str_detect(dossier, "_Manip") ~ "AGAP",
    str_detect(dossier, "Test") ~ "AGAP",
    TRUE ~ NA_character_)
  data$etat <- "Meso_frais"
  return(data)
})

### clean des spectres sans nom (erreur manip)
Xvalue2024_fruit <- Xvalue2024_fruit %>% 
  filter(!str_detect(spname, "Spectrum|blanc|test nettoyage")) %>% 
  mutate(
    ech = sub("-.*", "", spname),
    rep = as.numeric(substr(spname, 
                            nchar(spname)-4, 
                            nchar(spname)
                            )))
Xvalue2025_fruit <- Xvalue2025_fruit %>% 
  filter(!str_detect(spname, "Spectrum|blanc|test nettoyage")) %>% 
  mutate(
    ech = sub("-.*", "", spname),
    rep = as.numeric(substr(spname, 
                            nchar(spname)-4, 
                            nchar(spname)
                            )))
Xvalue2026_fruit <- Xvalue2026_fruit %>% 
  filter(!str_detect(spname, "Spectrum|blanc|test nettoyage")) %>% 
  mutate(
    ech = sub("-.*", "", spname),
    rep = as.numeric(substr(spname, 
                            nchar(spname)-4, 
                            nchar(spname)
                            )))
Xvalue2026_fruit_spe <- Xvalue2026_fruit_spe %>%
  filter(!str_detect(spname, "Spectrum|blanc|test nettoyage")) %>% 
  mutate(
    ech = sub("-.*", "", spname),
    rep = as.numeric(substr(spname, 
                            nchar(spname)-4, 
                            nchar(spname)
                            )))

### clean noms colonnes
Xvalue2024_fruit <- Xvalue2024_fruit %>% 
  rename_with(~ str_remove_all(.x, "(?i)_Vitaspec")) %>% 
  select(-2)
Xvalue2025_fruit <- Xvalue2025_fruit %>% 
  rename_with(~ str_remove_all(.x, "(?i)_Vitaspec")) %>% 
  select(-2)
Xvalue2026_fruit <- Xvalue2026_fruit %>% 
  rename_with(~ str_remove_all(.x, "(?i)_Vitaspec"))
Xvalue2026_fruit_spe <- Xvalue2026_fruit_spe %>% 
  rename_with(~ str_remove_all(.x, "(?i)_Vitaspec"))





#HUILES
### Load spectra
dirs2024_HR <- list.dirs(paste0(d0, "spectres/"), recursive = FALSE) %>%
  basename() %>%                     # recup le nom des dossiers
  as_tibble() %>%                    # tibble pour dyplr
  filter(grepl("_Vita", value)) %>%  
  filter(grepl("HR", value)) %>% 
  filter(grepl("2024",value)) %>% 
  pull(value)                        # retours sous forme de liste

dirs2025_HR <- list.dirs(paste0(d0,"spectres/"), recursive = FALSE) %>% 
  basename() %>%                     # recup le nom des dossiers
  as_tibble() %>%                    # tibble pour dyplr
  filter(grepl("_Vita", value)) %>%
  filter(grepl("HR", value)) %>%
  filter(grepl("2025",value)) %>% 
  pull(value) 

### merge de tous les campagnes de spectres
Xvalue2024_HR <- map_dfr(dirs2024_HR, function(dossier) {
  data <- vitaspec_load(paste0(d0, "spectres/"), dossier)
  data$campagne <- 2024
  data$source <- case_when(
    str_detect(dossier, "_AGAP") ~ "AGAP",
    str_detect(dossier, "_DIADE") ~ "DIADE",
    TRUE ~ NA_character_)
  data$etat <- "HR"
  return(data)
})
Xvalue2025_HR <- map_dfr(dirs2025_HR, function(dossier) {
  data <- vitaspec_load(paste0(d0, "spectres/"), dossier)
  data$campagne <- 2025
  data$source <- case_when(
    str_detect(dossier, "AGAP") ~ "AGAP",
    str_detect(dossier, "DIADE") ~ "DIADE",
    TRUE ~ NA_character_)
  data$etat <- "HR"
  return(data)
})

### clean des spectres sans nom (erreur manip)
Xvalue2024_HR <- Xvalue2024_HR %>% 
  filter(!str_detect(spname, "Spectrum|blanc|test nettoyage|^73-")) %>% 
  mutate(
    ech = sub("-.*", "", spname),
    rep = as.numeric(str_extract(spname, "(?<=0)[1-9][0-9]*$"))
  )
Xvalue2025_HR <- Xvalue2025_HR %>% 
  filter(
    !str_detect(spname, "Spectrum|blanc|test nettoyage|^165-|^73-"),
    spname != "139-HR-29-400006"
  ) %>% 
  mutate(
    ech = sub("-.*", "", spname),
    rep = as.numeric(str_extract(spname, "(?<=0)[1-9][0-9]*$"))
  )
### clean noms colonnes
Xvalue2024_HR <- Xvalue2024_HR %>% 
  rename_with(~ str_remove_all(.x, "(?i)_Vitaspec")) %>% 
  select(-2)
Xvalue2025_HR <- Xvalue2025_HR %>% 
  rename_with(~ str_remove_all(.x, "(?i)_Vitaspec")) %>% 
  select(-2)

```


# Cross Validation
## Prep data 
```{r, echo=FALSE, warning=FALSE, results='asis'}
### spectres
source(paste0(d0,"vitaspec_R/Rosa_vitaSPEC/compile_spectres.R"))


## FRAIS
Meso_frais_24_matrix <- compile_spectres_matrix(Xvalue2024_fruit,colonnes_spectres = c("x20240325_Pobe"),filtre_etat = "Meso_frais")
Meso_frais_25_matrix <- compile_spectres_matrix(Xvalue2025_fruit,colonnes_spectres = c("x20250224_Pobe"),filtre_etat = "Meso_frais")
Meso_frais_26_matrix <- compile_spectres_matrix(Xvalue2026_fruit,colonnes_spectres = c("x20260224_Pobe_AGAP","x20260225_Pobe_AGAP","x20260226_Pobe_AGAP"),filtre_etat = "Meso_frais")
Meso_frais_2425_matrix <- compile_spectres_matrix(Xvalue2024_fruit,Xvalue2025_fruit,colonnes_spectres = c("x20240325_Pobe","x20250224_Pobe"),filtre_etat = "Meso_frais")
Meso_frais_242526_matrix <- compile_spectres_matrix(Xvalue2024_fruit,Xvalue2025_fruit,Xvalue2026_fruit,colonnes_spectres = c("x20240325_Pobe","x20250224_Pobe","x20260224_Pobe_AGAP","x20260225_Pobe_AGAP","x20260226_Pobe_AGAP"),filtre_etat = "Meso_frais")

# write.csv(Meso_frais_242526_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/Meso_frais_242526.csv"),row.names = FALSE)



##SEC
#DIADE
Meso_sec_24_DIADE_matrix <- compile_spectres_matrix(Xvalue2024_fruit,colonnes_spectres = c("x20240405_S_DIADE"),filtre_etat = "Meso_Silica")
Meso_sec_25_DIADE_matrix <- compile_spectres_matrix(Xvalue2025_fruit,colonnes_spectres = c("x20250313_S_DIADE"),filtre_etat = "Meso_Silica")
Meso_sec_26_DIADE_matrix <- compile_spectres_matrix(Xvalue2026_fruit,colonnes_spectres = c("x20260304_S_DIADE","x20260305_S_DIADE","x20260306_S_DIADE","x20260309_R6_FACILE_S_DIADE","x20260309_R7_FACILE_S_DIADE"),filtre_etat = "Meso_Silica")
Meso_sec_2425_DIADE_matrix <- compile_spectres_matrix(Xvalue2024_fruit,Xvalue2025_fruit,colonnes_spectres = c("x20240405_S_DIADE","x20250313_S_DIADE"),filtre_etat = "Meso_Silica")
Meso_sec_242526_DIADE_matrix <- compile_spectres_matrix(Xvalue2024_fruit,Xvalue2025_fruit,Xvalue2026_fruit,colonnes_spectres = c("x20240405_S_DIADE","x20250313_S_DIADE","x20260304_S_DIADE","x20260305_S_DIADE","x20260306_S_DIADE","x20260309_R6_FACILE_S_DIADE","x20260309_R7_FACILE_S_DIADE"),filtre_etat = "Meso_Silica")
  
# write.csv(Meso_sec_24_DIADE_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/Meso_sec_24_DIADE.csv"),row.names = FALSE)

#AGAP
Meso_sec_24_AGAP_matrix <- compile_spectres_matrix(Xvalue2024_fruit,colonnes_spectres = c("x20240405_S_AGAP"),filtre_etat = "Meso_Silica")
Meso_sec_25_AGAP_matrix <- compile_spectres_matrix(Xvalue2025_fruit,colonnes_spectres = c("x20250313_S_AGAP"),filtre_etat = "Meso_Silica")
Meso_sec_2425_AGAP_matrix <- compile_spectres_matrix(Xvalue2024_fruit,Xvalue2025_fruit,colonnes_spectres = c("x20240405_S_AGAP","x20250313_S_AGAP"),filtre_etat = "Meso_Silica")

# write.csv(Meso_sec_2425_AGAP_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/Meso_sec_2425_AGAP.csv"),row.names = FALSE)

#TOT
Meso_sec_24_TOT_matrix <- compile_spectres_matrix(Xvalue2024_fruit,colonnes_spectres = c("x20240405_S_DIADE","x20240405_S_AGAP"),filtre_etat = "Meso_Silica")
Meso_sec_25_TOT_matrix <- compile_spectres_matrix(Xvalue2025_fruit,colonnes_spectres = c("x20250313_S_DIADE","x20250313_S_AGAP"),filtre_etat = "Meso_Silica")
Meso_sec_2425_TOT_matrix <- compile_spectres_matrix(Xvalue2024_fruit,Xvalue2025_fruit,colonnes_spectres = c("x20240405_S_DIADE","x20250313_S_DIADE","x20240405_S_AGAP","x20250313_S_AGAP"),filtre_etat = "Meso_Silica")

# write.csv(Meso_sec_2425_TOT_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/Meso_sec_2425_TOT.csv"),row.names = FALSE)



##LYOPH
#DIADE
Meso_lyoph_25_DIADE_matrix <- compile_spectres_matrix(Xvalue2025_fruit,colonnes_spectres = c("x20250319_Lyoph_DIADE","x20250321_Lyoph_DIADE"),filtre_etat = "Meso_Lyoph")

#AGAP
Meso_lyoph_25_AGAP_matrix <- compile_spectres_matrix(Xvalue2025_fruit,colonnes_spectres = c("x20250319_Lyoph_AGAP","x20250321_Lyoph_AGAP"),filtre_etat = "Meso_Lyoph")

Meso_lyoph_25_TOT_matrix <- compile_spectres_matrix(Xvalue2025_fruit,colonnes_spectres = c("x20240405_S_DIADE","x20250313_S_DIADE","x20240405_S_AGAP","x20250313_S_AGAP"),filtre_etat = "Meso_Lyoph")

# write.csv(Meso_lyoph_25_TOT_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/Meso_lyoph_25_TOT.csv"),row.names = FALSE)



##EXO
# Exo_frais_matrix <- compile_spectres_matrix(Xvalue_fruit,c("x20240325_Pobe","x20250224_Pobe"),filtre_etat = "Exo")
# Exo_frais_df <- compile_spectres_df(Xvalue_fruit,c("x20240325_Pobe","x20250224_Pobe"),filtre_etat = "Exo")


##HYUILE
#DIADE
HR_24_DIADE_matrix <- compile_spectres_matrix(Xvalue2024_HR,colonnes_spectres = c("x20240424_DIADE","x20241209_DIADE"),filtre_etat = "HR")
HR_25_DIADE_matrix <- compile_spectres_matrix(Xvalue2025_HR,colonnes_spectres = c("x20250317_DIADE","x20250603_DIADE","x20250908_DIADE","x20250909_DIADE"),filtre_etat = "HR")
HR_2425_DIADE_matrix <- compile_spectres_matrix(Xvalue2024_HR,Xvalue2025_HR,colonnes_spectres = c("x20240424_DIADE","x20241209_DIADE","x20250317_DIADE","x20250603_DIADE","x20250908_DIADE","x20250909_DIADE"),filtre_etat = "HR")

# write.csv(HR_2425_DIADE_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/HR_2425_DIADE.csv"),row.names = FALSE)
# write_xlsx(HR_2425_DIADE_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/HR_2425_DIADE.xlsx"))

#AGAP
HR_24_AGAP_matrix <- compile_spectres_matrix(Xvalue2024_HR,colonnes_spectres = c("x20240424_AGAP","x20241209_AGAP"),filtre_etat = "HR")
HR_25_AGAP_matrix <- compile_spectres_matrix(Xvalue2025_HR,colonnes_spectres = c("x20250317_AGAP"),filtre_etat = "HR")
HR_2425_AGAP_matrix <- compile_spectres_matrix(Xvalue2024_HR,Xvalue2025_HR,colonnes_spectres = c("x20240424_AGAP","x20241209_AGAP","x20250317_AGAP"),filtre_etat = "HR")

# write.csv(HR_2425_AGAP_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/HR_2425_AGAP.csv"),row.names = FALSE)

# TOT
HR_24_TOT_matrix <- compile_spectres_matrix(Xvalue2024_HR,colonnes_spectres = c("x20240424_DIADE","x20241209_DIADE","x20240424_AGAP","x20241209_AGAP"),filtre_etat = "HR")
HR_25_TOT_matrix <- compile_spectres_matrix(Xvalue2025_HR,colonnes_spectres = c("x20250317_DIADE","x20250603_DIADE","x20250908_DIADE","x20250909_DIADE","x20250317_AGAP"),filtre_etat = "HR")
HR_2425_TOT_matrix <- compile_spectres_matrix(Xvalue2024_HR,Xvalue2025_HR,colonnes_spectres = c("x20240424_DIADE","x20241209_DIADE","x20240424_AGAP","x20241209_AGAP","x20250317_DIADE","x20250603_DIADE","x20250908_DIADE","x20250909_DIADE","x20250317_AGAP"),filtre_etat = "HR")

# write.csv(HR_2425_TOT_matrix, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/HR_2425_TOT.csv"),row.names = FALSE)



### MEAN
mean_spectres_matrix <- function(data){
  data %>%
    group_by(ech) %>%
    summarise(
      x = matrix(colMeans(x, na.rm = TRUE), nrow = 1),
      .groups = "drop"
    )
  }
mean_spectres_df <- function(data){
  data %>% 
    select(-rep) %>% 
    group_by(ech) %>% 
    summarise(
      across(where(is.numeric), ~ mean(.x, na.rm = TRUE)),
      .groups = "drop")
  }




mean_Meso_frais_24 <- mean_spectres_matrix(Meso_frais_24_matrix)
mean_Meso_frais_25 <- mean_spectres_matrix(Meso_frais_25_matrix)
mean_Meso_frais_26 <- mean_spectres_matrix(Meso_frais_26_matrix)
mean_Meso_frais_2425 <- mean_spectres_matrix(Meso_frais_2425_matrix)
mean_Meso_frais_242526 <- mean_spectres_matrix(Meso_frais_242526_matrix)


mean_Meso_sec_24_DIADE <- mean_spectres_matrix(Meso_sec_24_DIADE_matrix)
mean_Meso_sec_25_DIADE <- mean_spectres_matrix(Meso_sec_25_DIADE_matrix)
mean_Meso_sec_26_DIADE <- mean_spectres_matrix(Meso_sec_26_DIADE_matrix)
mean_Meso_sec_2425_DIADE <- mean_spectres_matrix(Meso_sec_2425_DIADE_matrix)
mean_Meso_sec_242526_DIADE <- mean_spectres_matrix(Meso_sec_242526_DIADE_matrix)

mean_Meso_sec_24_AGAP <- mean_spectres_matrix(Meso_sec_24_AGAP_matrix)
mean_Meso_sec_25_AGAP <- mean_spectres_matrix(Meso_sec_25_AGAP_matrix)
mean_Meso_sec_2425_AGAP <- mean_spectres_matrix(Meso_sec_2425_AGAP_matrix)

mean_Meso_sec_24_TOT <- mean_spectres_matrix(Meso_sec_24_TOT_matrix)
mean_Meso_sec_25_TOT <- mean_spectres_matrix(Meso_sec_25_TOT_matrix)
mean_Meso_sec_2425_TOT <- mean_spectres_matrix(Meso_sec_2425_TOT_matrix)


mean_Meso_lyoph_25_DIADE <- mean_spectres_matrix(Meso_lyoph_25_DIADE_matrix)
mean_Meso_lyoph_25_AGAP <- mean_spectres_matrix(Meso_lyoph_25_AGAP_matrix)
mean_Meso_lyoph_25_TOT <- mean_spectres_matrix(Meso_lyoph_25_TOT_matrix)


mean_HR_24_DIADE <- mean_spectres_matrix(HR_24_DIADE_matrix)
mean_HR_25_DIADE <- mean_spectres_matrix(HR_25_DIADE_matrix)
mean_HR_2425_DIADE <- mean_spectres_matrix(HR_2425_DIADE_matrix)

mean_HR_24_AGAP <- mean_spectres_matrix(HR_24_AGAP_matrix)
mean_HR_25_AGAP <- mean_spectres_matrix(HR_25_AGAP_matrix)
mean_HR_2425_AGAP <- mean_spectres_matrix(HR_2425_AGAP_matrix)

mean_HR_24_TOT <- mean_spectres_matrix(HR_24_TOT_matrix)
mean_HR_25_TOT <- mean_spectres_matrix(HR_25_TOT_matrix)
mean_HR_2425_TOT <- mean_spectres_matrix(HR_2425_TOT_matrix)

# write.csv(mean_HR_25_TOT, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/X/mean_HR_25_TOT.csv"),row.names = FALSE)



### chimie

# le fichier Yvalue modifié avec les 4 variables carotene en plus 
Y <- read.xlsx(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques_new_FRUIT.xlsx")) 
Y_HR <- read.xlsx(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/Analyses_chimiques_4var_en_plus_HR.xlsx"))

Y_HR <- Y_HR

ag <- Y %>%
  select(2:21) %>%
  colnames()
ag_HR <- Y_HR %>% 
  select(2:24) %>% 
  colnames()

# write.csv(ag, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/CLUSTER/modele_pls/ag.csv"),row.names = FALSE)
# write.csv(ag, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/ag.csv"),row.names = FALSE)

join <- function(data){
  data %>% 
    left_join(Y, by = "ech")
}
join_HR <- function(data){
  data %>% 
    left_join(Y_HR, by = "ech")
}

# dat <- join(mean_Meso_frais_24)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_frais_24.csv"),row.names = FALSE)
# dat <- join(mean_Meso_frais_25)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_frais_25.csv"),row.names = FALSE)
# dat <- join(mean_Meso_frais_26)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_frais_26.csv"),row.names = FALSE)
# dat <- join(mean_Meso_frais_2425)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_frais_2425.csv"),row.names = FALSE)
# dat <- join(mean_Meso_frais_242526)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_frais_242526.csv"),row.names = FALSE)


# dat <- join(mean_Meso_sec_24_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_24_DIADE.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_25_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_25_DIADE.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_26_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_26_DIADE.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_2425_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_2425_DIADE.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_242526_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_242526_DIADE.csv"),row.names = FALSE)
# 
# dat <- join(mean_Meso_sec_24_AGAP)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_24_AGAP.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_25_AGAP)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_25_AGAP.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_2425_AGAP)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_2425_AGAP.csv"),row.names = FALSE)
#
# dat <- join(mean_Meso_sec_24_TOT)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_24_TOT.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_25_TOT)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_25_TOT.csv"),row.names = FALSE)
# dat <- join(mean_Meso_sec_2425_TOT)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_sec_2425_TOT.csv"),row.names = FALSE)


# dat <- join(mean_Meso_lyoph_25_DIADE) 
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_lyoph_25_DIADE.csv"),row.names = FALSE)
#
# dat <- join(mean_Meso_lyoph_25_AGAP) 
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_lyoph_25_AGAP.csv"),row.names = FALSE)
#
# dat <- join(mean_Meso_lyoph_25_TOT)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_mean_Meso_lyoph_25_TOT.csv"),row.names = FALSE)


# dat <- join_HR(mean_HR_24_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_24_DIADE.csv"),row.names = FALSE)
# dat <- join_HR(mean_HR_25_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_25_DIADE.csv"),row.names = FALSE)
# dat <- join_HR(mean_HR_2425_DIADE)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_2425_DIADE.csv"),row.names = FALSE)
# 
# dat <- join_HR(mean_HR_24_AGAP)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_24_AGAP.csv"),row.names = FALSE)
# dat <- join_HR(mean_HR_25_AGAP)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_25_AGAP.csv"),row.names = FALSE)
# dat <- join_HR(mean_HR_2425_AGAP)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_2425_AGAP.csv"),row.names = FALSE)
# 
# dat <- join_HR(mean_HR_24_TOT)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_24_TOT.csv"),row.names = FALSE)
# dat <- join_HR(mean_HR_25_TOT)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_25_TOT.csv"),row.names = FALSE)
# dat <- join_HR(mean_HR_2425_TOT)
# write.csv(dat, paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_HR_2425_TOT.csv"),row.names = FALSE)


```

## CV
```{r echo=FALSE, warning=FALSE, results='asis'}
source(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/calibrations/list_pre_test_carot.R "))
source(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/calibrations/list_pre_test_AG.R"))

source(paste0(d0,"vitaspec_R/vitaspec_preCV.R"))
source(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/new_preCV.R"))
source(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/new_new_preCV.R"))

source(paste0(d0,"vitaspec_R/Rosa_vitaSPEC/compile_spectres.R"))
source(paste0(d0,"vitaspec_R/Rosa_vitaSPEC/get_best_wold.R"))

rpd <- rchemo::rpd
S0 <- "C:/Users/U108-N806/Documents/STAGE_M2_ROSA_NIRS/VitaSPEC/vitaspec_R/ROSA_VitaSPEC/Results/test_pretraitements/"

fm_all=list()
id_model=list()
#idparam <- "meso_frais"
idparam <- "meso_silica"
set.seed(123)

# ag2 <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/CLUSTER/modele_pls/ag.csv"),
#                  sep=";", 
#                  header=TRUE, 
#                  dec=",")
# ag3 <- ag2$x

dat2 <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat_sec_DIADE_matrix.csv"),
                  sep = ",",
                  header = TRUE,
                  dec = ".")
dat3 <- read.xlsx(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/CLUSTER/modele_pls/dat_sec_DIADE_matrix.csv"))

#source(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/list_pre_beta_carot.R"))
ncomp = 15
compose_etudie <- ag[-c(3:20)]
print(compose_etudie)

for (k in compose_etudie){
files <- paste0(S0,k)

  if (!dir.exists(files)) {
    dir.create(files, recursive = TRUE)}
}

  compose_etudie %>%
    walk(function(ag1) {
      print(ag1)
      datok <- dat %>%
        filter(!is.na(.data[[ag1]]))
      
      y_vals <- as.numeric(datok[[ag1]])
      x_mat  <- as.matrix(datok$x)

      # try({
      #   vitaspec_preCV(
      #     x = x_mat,
      #     y = y_vals,
      #     list_pre = list_pre_test_AG,
      #     ncomp = ncomp, 
      #     titl = "Meso_sec",
      #     y_name = ag1,
      #   )
      # })
      try({
        new_new_preCV(
          data = datok,
          x = x_mat,
          y = y_vals,
          list_pre = list_pre_test_AG,
          ncomp = ncomp,
          seg = 10,
          titl = "Meso_sec",
          y_name = ag1,
          rep = 50,
          sortie = "C:/Users/U108-N806/Documents/STAGE_M2_ROSA_NIRS/VitaSPEC/vitaspec_R/ROSA_VitaSPEC/Results/test_pretraitements/")
        })
    })

```

## comparaison pretraitements
```{r}
d0 <- "C:/Users/U108-N806/Documents/STAGE_M2_ROSA_NIRS/VitaSPEC/"
SEC <- "vitaspec_R/ROSA_vitaSPEC/Results/test_pretraitements/175pretrait/SEC/"
HR <- "vitaspec_R/ROSA_vitaSPEC/Results/test_pretraitements/175pretrait/HR/"
FRAIS <- "vitaspec_R/ROSA_vitaSPEC/Results/test_pretraitements/175pretrait/FRAIS/"

ncomp = 15
compose_etudie <- ag #ag_HR

V <- SEC

for (k in compose_etudie){
files <- k

  list_tab <- list.files(paste0(d0,V,files),
                         pattern = "\\.xlsx$",
                         full.names = FALSE)
  list_tab_clean <- gsub("\\.xlsx$", "", list_tab)
  
  for (i in 1:length(list_tab_clean)){
    tab <- readxl::read_excel(paste0(d0,V,files,"/",list_tab_clean[i],".xlsx"))
    colnames(tab)[1] <- "Repetition"
    colnames(tab)[2] <- "Pretraitement"
  
    tab_moy <- tab %>% 
      distinct(Pretraitement, Repetition, .keep_all = TRUE) %>% 
      group_by(Pretraitement) %>%
      summarise(
        onesigma_Ncomp = paste(onesigma_Ncomp, collapse = ", "),
        Wold_Ncomp = paste(Wold_Ncomp, collapse = ", "),
        across(-c(Repetition, onesigma_Ncomp, Wold_Ncomp), ~ mean(.x, na.rm = TRUE)),
        .groups = "drop"
      )
    write_xlsx(tab_moy, paste0(d0,V,files,"/",list_tab_clean[i],"_moy",".xlsx"))
  
    tab_R2 <- tab_moy %>% 
      select(Pretraitement, ends_with("R2") & -contains ("cv"))
    write_xlsx(tab_R2, paste0(d0,V,files,"/",list_tab_clean[i],"_moy_R2",".xlsx"))
    
    tab_ADJR2 <- tab_moy %>% 
      select(Pretraitement, contains ("R2cv"))
    write_xlsx(tab_ADJR2, paste0(d0,V,files,"/",list_tab_clean[i],"_moy_R2cv",".xlsx"))
    
    tab_RMSEP <- tab_moy %>% 
      select(Pretraitement, contains("RMSEcv"))
    write_xlsx(tab_RMSEP, paste0(d0,V,files,"/",list_tab_clean[i],"_moy_RMSEcv",".xlsx"))
    
    tab_diff <- tab_moy
    for(d in 0:ncomp) {
      col_r2   <- paste0("LV", d, "_R2")
      col_adj  <- paste0("LV", d, "_R2cv")
      col_diff <- paste0("LV", d, "_diff")
  
      if (col_r2 %in% names(tab_diff) && col_adj %in% names(tab_diff)) {
        tab_diff <- tab_diff %>% 
          mutate(!!col_diff := .data[[col_r2]] - .data[[col_adj]])
      } else {
        message(paste(d, "colonnes non trouvées"))
      }
    }
  
    tab_diff <- tab_diff %>% 
      select(-contains("RMSEcv")) %>% 
      select(Pretraitement,contains("diff")) %>% 
      write_xlsx(paste0(d0,V,files,"/",list_tab_clean[i],"_moy_diff",".xlsx"))
  }
}
```
 
## Calibration finale
```{r, echo=FALSE, warning=FALSE, results='asis'}
param=read.csv(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/calibrations/Vitaspec_fruit_param.csv"))
#source(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/calibrations/list_pre_test_carot.R"))

  
fm_all=list()
id_model=list()
idparam <- "meso_frais"
# idparam <- "HR"

ncomp <- 15
compose_etudie <- ag#ag_HR

dat <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_Meso_frais_2425.csv"),
                  sep = ",",
                  header = TRUE,
                  dec = ".")

compose_etudie %>% 
  walk(function(ag1) {
    print(ag1)
    datok <- dat %>% 
      filter(!is.na(.data[[ag1]]))
  
    y_vals <- as.numeric(datok[[ag1]])
    x_mat <- as.matrix(datok %>% select(starts_with("x", ignore.case = FALSE)))
    seg <- 10
    
    current_param <- param %>%
      filter(str_detect(Cal_data, stringr::fixed(idparam)),  
             str_trim(Propriete) == str_trim(ag1))

    if (nrow(current_param) == 0) {
      warning(paste("error no", idparam, "for", ag1))
    } else {
      p <- eval(parse(text = current_param$pre))
      n_lv <- current_param$nvl
      
      xp = pre(x_mat, p)
      df_temp <- data.frame(y = y_vals)
      df_temp$xp <- xp
      
      n <- nrow(datok)
      segs <- cvsegments(n, seg)
      
      fm_finale <- plsr(y ~ xp, data = df_temp, ncomp = ncomp, scale = FALSE, validation = "CV", segments = segs)
    
      fm_all <<- append(fm_all, list(fm_finale))
      id_model <<- id_model %>%
      bind_rows(tibble(Propriete = ag1,
                       Condition = idparam))
      
      res_rmsep <- RMSEP(fm_finale, estimate = "CV")$val[1, 1, -1] 
      res_r2_adj <- R2(fm_finale, estimate = "CV")$val[1, 1, -1]
      res_r2 <- R2(fm_finale, estimate = "train")$val[1, 1, -1]
      x_comps <- 1:(length(res_r2))
      
      nom_pdf <- paste0(d0,"vitaspec_R/ROSA_VitaSPEC/save/", "graphiques_",ag1, ".pdf")
      pdf(file = nom_pdf, width = 8, height = 6)
      
      ## graph 1
      par(mar = c(5, 4, 4, 4) + 0.3)
      
      # recup nom pre
      titre_elements <- c()

      n_etapes <- ifelse(is.matrix(p), nrow(p), length(p))
      
      for (i in 1:n_etapes) {
        if (is.matrix(p)) {
          nom <- p[i, 1][[1]]
          args <- p[i, 2][[1]]
        } else {
          nom <- p[[i]][[1]]
          args <- p[[i]][[2]]
        }
        if (is.null(args) || (is.character(args) && all(args == ""))) {
          titre_elements <- c(titre_elements, nom)
        } else {
          args_txt <- paste0("c(", paste(args, collapse = ","), ")")
          titre_elements <- c(titre_elements, paste0(nom, "_", args_txt))
        }
      }
      texte_p <- paste(titre_elements, collapse = "_")
    
      bestncomp_global <- selectNcomp(fm_finale, method = "onesigma", plot = TRUE, 
                                    main = ag1)
      mtext(paste0("Prétraitement : ",texte_p), side = 3, line = 0.5, cex = 0.75)
    
      par(new = TRUE)
    
      # R2
      plot(x_comps, res_r2, type = "b", col = "#90C987", pch = 17, lty = 2, lwd = 2,
         axes = FALSE, xlab = "", ylab = "", ylim = c(0, 1)) 
    
      # ADJR2
      lines(x_comps, res_r2_adj, type = "b", col = "#4eb265", pch = 16, lty = 1, lwd = 2)
    
      # axe
      axis(4, col = "black", col.axis = "black")
      mtext("R2", side = 4, line = 2.5, col = "black", cex = 0.9)
    
      # legende
      legend("top", bty = "n", cex = 0.8,
             legend = c("RMSEcv", "R2", "ADJR2"), 
            col = c("black", "#90C987", "#4eb265"), 
            pch = c(1, 17, 16), 
            lty = c(1, 2, 1),
            lwd = c(1, 2, 2))
      
      ## graph2
      valeur_r2_adj <- round(res_r2_adj[n_lv], 3)
      valeur_rmsecv <- round(res_rmsep[n_lv], 3)
      
      texte <- paste0("n_comp = ", n_lv,
                      "\nR2_cv = ", valeur_r2_adj, 
                      "\nRMSEcv = ", valeur_rmsecv,
                      "\nn_ech = ", n)
      
      valeurs_predites <- as.vector(fm_finale$validation$pred[, 1, ncomp])
      
      df_plot <- data.frame(Mesuree = y_vals, 
                            Predite = valeurs_predites)
      
      graph_2 <- ggplot(df_plot, aes(x = Predite, y = Mesuree)) +
        geom_point(shape = 1, alpha = 0.6) +
        geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
        geom_smooth(method = "lm", color = "blue", se = FALSE, linewidth = 0.5) +
        annotate("text", 
                 x = -Inf, y = Inf,          
                 hjust = 0, vjust = 1.5,  
                 label = texte, 
                 size = 4.5) +
        labs(title = paste("Prédictions vs Mesures :", ag1),
             x = "Valeurs Prédites",
             y = "Valeurs Mesurées")
      print(graph_2)
      
      dev.off()
    }
    }
    )
save(fm_all, id_model, file = paste0(d0, "vitaspec_R/ROSA_vitaSPEC/models/Vitaspec_fruit_model_def_frais"))
```

## nouveaux Y sur 2024-2025
```{r}

library(ggpmisc)
library(ggrepel)

## comparaison valeurs des Y
new_carot <- read.xlsx(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/new_carot_fruits.xlsx")) %>% 
  mutate(ech = sub("-.*", "", code_nirs)) %>% 
  select(-c(1,2))
old_carot <- read.table(paste0(d0,"vitaspec_R/analyses_ref_csv/Partie 1.3.csv"),
                     sep=";", 
                     header=TRUE, 
                     dec=",") %>%
   mutate(ech = sub("-.*", "", code_nirs)) %>% 
   select(-c(1,2))

new_carot_commun <- semi_join(new_carot, old_carot, by = "ech")
new_carot_reste <- anti_join(new_carot, old_carot, by = "ech")

old_carot <- old_carot %>%
  filter(ech %in% new_carot_commun$ech) %>%
  mutate(Origine = "Old") %>% 
  rename(trans.alpha.carotene = trans.alpha.carotne,
         total.beta.carotene = total.beta.carotenes,
         total.carotene = total.carotenes)
new_carot_commun <- new_carot_commun %>%
  mutate(Origine = "New") %>% 
  rename(trans.alpha.carotene = `trans-alpha-carotène`,
         trans.beta.carotene = `trans-beta-carotène`,
         X13.cis.beta.carotene = `13.cis-beta-carotène`,
         X9.cis.beta.carotene = `9.cis-beta-carotène`,
         total.beta.carotene = `total.beta-carotènes`,
         total.carotene = total.carotènes)
data_plot <- bind_rows(old_carot, new_carot_commun)

data_long <- data_plot %>%
  pivot_longer(
    cols = -c(ech, Origine), 
    names_to = "Variable", 
    values_to = "Valeur")

variables <- unique(data_long$Variable)

tab_diff_moy <- data_plot %>%
  pivot_longer(cols = -c(ech, Origine), names_to = "Variable", values_to = "Valeur") %>%
  pivot_wider(names_from = Origine, values_from = Valeur) %>%
  mutate(diff = Old - New) %>%
  group_by(Variable) %>%
  summarise(diff_moy = sum(diff, na.rm = TRUE) / n(), .groups = "drop") %>%
  pivot_wider(names_from = Variable, values_from = diff_moy) %>% 
  relocate(trans.alpha.carotene,trans.beta.carotene,X9.cis.beta.carotene,X13.cis.beta.carotene,total.beta.carotene,total.carotene)


#graph comparaison old/new
mon_theme <- theme_bw() + 
  theme(
    plot.title = element_text(size = 14, hjust = 0, face = "bold", margin = margin(b = 15)),
    strip.background = element_rect(fill = "gray85", color = "black"),
    strip.text = element_text(size = 11, color = "black"),
    panel.border = element_rect(color = "black", fill = NA),
    panel.grid.major = element_line(color = "gray90"),
    panel.grid.minor = element_line(color = "gray95"),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 6),
    legend.position = "bottom")

p_page1 <- data_long %>%
  filter(Variable %in% variables[1:3]) %>%
  ggplot(aes(x = ech, y = Valeur, color = Origine, fill = Origine)) +
  geom_line(aes(group = ech), color = "black", linewidth = 0.5) +
  geom_point(shape = 21, size = 2, color = "black", alpha = 0.8) +
  facet_wrap(~ Variable, scales = "free", ncol = 1) + 
  labs(title = "Comparaison old vs new", x = "Échantillons", y = "Valeur") +
  mon_theme
p_page2 <- data_long %>%
  filter(Variable %in% variables[4:6]) %>%
  ggplot(aes(x = ech, y = Valeur, color = Origine, fill = Origine)) +
  geom_line(aes(group = ech), color = "black", linewidth = 0.5) +
  geom_point(shape = 21, size = 2, color = "black", alpha = 0.8) +
  facet_wrap(~ Variable, scales = "free", ncol = 1) + 
  labs(title = "Comparaison old vs new", x = "Échantillons", y = "Valeur") +
  mon_theme

# pdf(file = paste0(d0, "vitaspec_R/ROSA_vitaSPEC/save/graphique_comparaison_new_carot_fruits.pdf"), 
#     width = 16,  
#     height = 10)  
# print(p_page1) 
# print(p_page2)
# dev.off()

#regression old/new
data_scatter <- data_plot %>%
  pivot_longer(cols = -c(ech, Origine), names_to = "Variable", values_to = "Valeur") %>%
  pivot_wider(names_from = Origine, values_from = Valeur) %>% 
  mutate(ech_clean = sub("^M", "", ech))
p3 <- ggplot(data_scatter, aes(x = Old, y = New)) +
  geom_point(shape = 1, alpha = 0.6) +
  geom_text_repel(aes(label = ech_clean), 
                  size = 3,            #taille du texte
                  segment.color = 'grey80', # ligne de liaison
                  force = 1,           
                  max.overlaps = 15) +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  geom_smooth(method = "lm", color = "blue", se = FALSE, linewidth = 0.5) +
  stat_poly_eq(aes(label = after_stat(rr.label)), 
               formula = y ~ x, 
               parse = TRUE, 
               label.x = "left", 
               label.y = "top") +
  facet_wrap(~ Variable, scales = "free", ncol = 3) + 
  theme_bw() +
  labs(
    title = "Comparaison Old vs New",
    x = "Old",
    y = "New"
  )

pdf(file = paste0(d0, "vitaspec_R/ROSA_vitaSPEC/save/pred_vs_mesure_new_carot_scatter.pdf"), 
    width = 16,  
    height = 10)  
print(p3) 
dev.off()


#graph histo
data_plot_graph <- data_plot %>%
  pivot_longer(cols = -c(ech, Origine), names_to = "compose", values_to = "Valeur") %>%
  pivot_wider(names_from = Origine, values_from = Valeur) %>%
  mutate(diff = Old - New) %>%
  group_by(compose) %>%
  summarise(
    diff_moy = mean(diff, na.rm = TRUE),
    min_diff = min(diff, na.rm = TRUE),
    valeurs_inchangees = sum(round(diff) == 0, na.rm = TRUE), 
    .groups = "drop") %>%
  mutate(Sens = ifelse(diff_moy > 0, "Positif", "Négatif"))


p2 <- ggplot(data_plot_graph, aes(x = compose, y = diff_moy, fill = Sens)) +
  geom_col(color = "black", width = 0.7) +
  geom_hline(yintercept = 0, color = "black", size = 1) +
  geom_text(aes(y = ifelse(diff_moy > 0, diff_moy, 0), 
                label = paste0("inchangés : ", valeurs_inchangees)),
            vjust = -0.8, size = 3.5, fontface = "italic", color = "darkgray") +
  geom_text(aes(y = ifelse(diff_moy < 0, diff_moy, 0), 
                label = paste0("min : ", round(min_diff, 2))),
            vjust = 1.8, size = 3.5, fontface = "italic", color = "black") +
  
  scale_fill_manual(values = c("Négatif" = "#90C987", "Positif" = "#4eb265")) +
  scale_y_continuous(expand = expansion(mult = c(0.15, 0.15))) +
  labs(title = "Différence moyenne",
       subtitle = "Calculée comme : valeur Old - valeur New",
       y = "Différence moyenne",
       x = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 11, face = "bold"),
    axis.title.y = element_text(size = 12),
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    legend.position = "bottom")

# pdf(file = paste0(d0, "vitaspec_R/ROSA_vitaSPEC/save/graphique_difference_carot.pdf"), 
#     width = 16,  
#     height = 10)  
# print(p2) 
# dev.off()


## comparaison nouveaux Y/pred
pred_silica <- readxl::read_excel(paste0(d0,"pred/Pobe_24-25_NIRS_Meso_Silica_pred_moy.xlsx"))
pred_silica2 <- pred_silica %>% 
  select(-c(2:10)) %>% 
  mutate(ech = sub("-.*", "", ech)) %>% 
  rename(trans.alpha.carotene = trans.alpha.carotne,
         total.beta.carotene = total.beta.carotenes,
         total.carotene = total.carotenes) %>% 
  select(-c(8))
         
new_carot_reste <- new_carot_reste %>% 
  rename(trans.alpha.carotene = `trans-alpha-carotène`,
         trans.beta.carotene = `trans-beta-carotène`,
         X13.cis.beta.carotene = `13.cis-beta-carotène`,
         X9.cis.beta.carotene = `9.cis-beta-carotène`,
         total.beta.carotene = `total.beta-carotènes`,
         total.carotene = total.carotènes)

pred_carot_reste <- semi_join(pred_silica2, new_carot_reste, by = "ech")

pred_carot_reste_long <- pred_carot_reste %>%
  pivot_longer(
    cols = -ech,
    names_to = "Compose",   
    values_to = "Predite"    
  )

new_carot_reste_long <- new_carot_reste %>%
  pivot_longer(
    cols = -ech,
    names_to = "Compose",
    values_to = "Mesuree"
  )

data_graph <- inner_join(pred_carot_reste_long, new_carot_reste_long, by = c("ech", "Compose"))

#GRAPH
p <- ggplot(data_graph, aes(x = Predite, y = Mesuree)) +
  geom_point(shape = 1, alpha = 0.6) +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  geom_smooth(method = "lm", color = "blue", se = FALSE, size = 0.5) +
  stat_poly_eq(aes(label = after_stat(rr.label)), 
               formula = y ~ x, 
               parse = TRUE, 
               label.x = "left", 
               label.y = "top") +
  facet_wrap(~ Compose, scales = "free", ncol = 3) + 
  theme_bw() +
  labs(
    title = "Mesocarpe - 24_25 - Nouvelles analyses carot",
    x = "Teneur Prédite par SPIR",
    y = "Teneur Mesuree"
  )

# ggsave("pred_vs_mesure_new_carot.pdf", plot = p, path = paste0(d0,"vitaspec_R/ROSA_vitaSPEC/save"),width = 12, height = 8)

```


## prediction de nouveaux échantillons 2026 - frais/sec
### METHODE 1
```{r}
# load(paste0(d0,"vitaspec_R/Vitaspec_fruit_models_3_sec"))
load(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/models/Vitaspec_fruit_model_def_sec"))

idparam <- "meso_silica" 
titre <- "SEC_26_NIRS_R5_Methode1_Meso_Sec"

param <- read.csv(paste0(d0, "vitaspec_R/Vitaspec_fruit_param.csv"))

# spectres a predire

f <- paste0(d0, "spectres/20260306_Vitaspec_S_DIADE")
spnew <- asd_read_dir(f) 
spnew <- spnew[!grepl("^[^-]+-S", rownames(spnew)),]

param_filtre <- param %>% 
  filter(grepl(idparam, Cal_data))

# fichier prédiction

pred <- tibble(spectrum = rownames(spnew)) %>% 
  mutate(
    régime = str_extract(spectrum, "^[^-]+"),                           # R5
    code1  = str_extract(spectrum, "(?<=-)[^-]+"),                      # L1H / L2H / L3H / L1M / L2M / L3M / pareil pour O
    zone   = substr(code1, 1, 2),                                       # L1 / L2 / L3 / O1 / O2 / O3
    lumière = substr(code1, 1, 1),                                      # L / O
    code2  = substr(str_extract(spectrum, "(?<=-)[^-]+$"), 1, 3),       # FE1 / FE2 / FK1 / FK2
    zone_régime = paste0("z",substr(code1, 2, 2)),                      # z1 / z2 / z3
    posi_epillet = substr(code1, 3, 3),                                 # H / M
    fruit = paste0("fruit",substr(code2,3,3)),                          # fruit1 / fruit2
    tissu = substr(code2, 2, 2),                                        # E / K
    de_ht_en_bas = as.numeric(str_extract(spectrum, "[1-9][0-9]*$")),    # 1 à 15
    `#fruit` = paste0(régime, "-", code1, str_extract(code2, "[0-9]")), # code petits pots
    ech = paste(régime, code1, code2, sep = "-")) %>%                 #ex : R5-L1H-FE1
  relocate(spectrum, régime, code1, zone, lumière, zone_régime, code2, posi_epillet, fruit, tissu, de_ht_en_bas,`#fruit`, ech)
  
# predictions
nag <- nrow(param_filtre)

for (i in 1:nag) {
  p <- eval(parse(text = param_filtre$pre[i]))
  spnx <- pre(spnew, p)
  
  prop <- param_filtre$Propriete[i]
  
  imodel <- which(grepl(idparam, id_model$Condition) & grepl(prop, id_model$Propriete))
  
  pred_val <- predict(fm_all[[imodel]], spnx)$pred
  pred <- pred %>% 
    mutate(!!prop := as.vector(pred_val))
}

pred <- pred %>%
  relocate(ech, .after = last_col())

# fichier moy par échantillon
mes_molecules <- param_filtre$Propriete

pred_moy <- pred %>%
  group_by(ech) %>%
  summarise(across(any_of(mes_molecules), ~ mean(.x, na.rm = TRUE)), .groups = "drop")

# fichier stats descriptives
pred_stats <- pred %>%
  select(ech, any_of(mes_molecules)) %>%
  pivot_longer(cols = -ech, names_to = "Variable", values_to = "Valeur") %>%
  group_by(ech, Variable) %>%
  summarise(
    mean = mean(Valeur, na.rm = TRUE),
    sd   = sd(Valeur, na.rm = TRUE),
    min  = min(Valeur, na.rm = TRUE),
    max  = max(Valeur, na.rm = TRUE),
    .groups = "drop"
  )

#export
write_xlsx(pred, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred.xlsx"))
write_xlsx(pred_moy, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred_moy.xlsx"))
write_xlsx(pred_stats, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred_stats.xlsx"))

```

### METHODE 2
```{r}
load(paste0(d0,"vitaspec_R/Vitaspec_fruit_models_3_sec"))

idparam <- "meso_silica" 
titre <- "SEC_26_NIRS_R7_Methode2_Meso_Sec"

param <- read.csv(paste0(d0, "vitaspec_R/Vitaspec_fruit_param.csv"))

# spectres a predire

f <- paste0(d0, "spectres/20260309_R7_FACILE_Vitaspec_S_DIADE")
spnew <- asd_read_dir(f) 
spnew <- spnew[grepl("^[^-]+-S", rownames(spnew)),]

param_filtre <- param %>% 
  filter(grepl(idparam, Cal_data))

# fichier prédiction

pred <- tibble(spectrum = rownames(spnew)) %>% 
  mutate(ech = sub("[0-9]+$", "", spectrum))             #ex : R5-S1-E

#prediction 
nag <- nrow(param_filtre)

for (i in 1:nag) {
  p <- eval(parse(text = param_filtre$pre[i]))
  spnx <- pre(spnew, p)
  
  prop <- param_filtre$Propriete[i]
  
  imodel <- which(grepl(idparam, id_model$Condition) & grepl(prop, id_model$Propriete))
  
  pred_val <- predict(fm_all[[imodel]], spnx)$pred
  pred <- pred %>% 
    mutate(!!prop := as.vector(pred_val))
}

pred <- pred %>%
  relocate(ech, .after = last_col())

# fichier moy par échantillon
mes_molecules <- param_filtre$Propriete

pred_moy <- pred %>%
  group_by(ech) %>%
  summarise(across(any_of(mes_molecules), ~ mean(.x, na.rm = TRUE)), .groups = "drop")

#fichier stats descriptives
pred_stats <- pred %>%
  select(ech, any_of(mes_molecules)) %>%
  pivot_longer(cols = -ech, names_to = "Variable", values_to = "Valeur") %>%
  group_by(ech, Variable) %>%
  summarise(
    mean = mean(Valeur, na.rm = TRUE),
    sd   = sd(Valeur, na.rm = TRUE),
    min  = min(Valeur, na.rm = TRUE),
    max  = max(Valeur, na.rm = TRUE),
    .groups = "drop"
  )

#export
write_xlsx(pred, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred.xlsx"))
write_xlsx(pred_moy, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred_moy.xlsx"))
write_xlsx(pred_stats, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred_stats.xlsx"))




```

## prediction de nouveaux échantillons 2026 - HR
```{r}

```

## prediction de 2024-2025 - frais/sec
```{r}
load(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/models/Vitaspec_fruit_model_def_HR"))

MAT <- read.table(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/Data/HR_2425_DIADE.csv"),
                     sep=",", 
                     header=TRUE, 
                     dec=".")
# write_xlsx(MAT, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/Data/dat/dat_Meso_sec_2425_DIADE.xlsx"))

idparam <- "HR" 
titre <- "HR"

param <- read.csv(paste0(d0, "vitaspec_R/ROSA_vitaSPEC/calibrations/Vitaspec_fruit_param.csv"))

# spectres a predire
MAT_matrix <- as.matrix(MAT[, 6:ncol(MAT)])

# noms_echantillons <- paste(MAT$source, MAT$etat, MAT$ech, MAT$rep, sep = "_") --> combine les colonnes de métadonnées pour créer un nom unique (ex: "DIADE_HR_1_1")
noms_echantillons <- paste(MAT$source, MAT$etat, MAT$ech, MAT$rep, sep = "_")
rownames(MAT_matrix) <- noms_echantillons

longueurs_onde <- 350:(350 + ncol(MAT_matrix) - 1)
colnames(MAT_matrix) <- as.character(longueurs_onde)


spnew <- MAT_matrix

param_filtre <- param %>% 
  filter(grepl(idparam, Cal_data))

# fichier prédiction

pred <- tibble(spectrum = rownames(spnew)) %>% 
  mutate(ech = sub("[0-9]+$", "", spectrum))

#prediction 
nag <- nrow(param_filtre)

# Notre boîte noire pour enregistrer le problème
erreur_info <- list() 

for (i in 1:nag) {
  p <- eval(parse(text = param_filtre$pre[i]))
  spnx <- pre(spnew, p)
  
  prop <- param_filtre$Propriete[i]
  
  imodel <- which(grepl(idparam, id_model$Condition) & grepl(prop, id_model$Propriete))
  
  if (length(imodel) == 0) next
  imodel <- imodel[1]
  
  if (is.null(fm_all[[imodel]])) next
  
  # ----- DÉTECTEUR DE CRASH V2 -----
  col_spnx <- ncol(spnx)
  col_mod <- length(fm_all[[imodel]]$Xmeans)
  
  if (col_spnx != col_mod) {
    # On sauvegarde toutes les infos dans la boîte noire
    erreur_info$molecule <- prop
    erreur_info$col_spnx <- col_spnx
    erreur_info$col_mod <- col_mod
    
    # On casse (arrête) la boucle en douceur, sans faire d'erreur fatale
    break 
  }
  # ------------------------------
  
  nvl <- param_filtre$nvl[i] 
  pred_val <- predict(fm_all[[imodel]], spnx, ncomp = nvl)
  
  pred <- pred %>% 
    mutate(!!prop := as.vector(pred_val))
}

# --- AFFICHAGE DE LA BOÎTE NOIRE ---
cat("\n=== RÉSULTAT DU DÉTECTEUR ===\n")
cat("Molécule qui plante :", erreur_info$molecule, "\n")
cat("Colonnes dans le spectre :", erreur_info$col_spnx, "\n")
cat("Colonnes attendues par le modèle :", erreur_info$col_mod, "\n")
cat("===============================\n")

pred <- pred %>%
  relocate(ech, .after = last_col())

# fichier moy par échantillon
mes_molecules <- param_filtre$Propriete

pred_moy <- pred %>%
  group_by(ech) %>%
  summarise(across(any_of(mes_molecules), ~ mean(.x, na.rm = TRUE)), .groups = "drop")

#fichier stats descriptives
pred_stats <- pred %>%
  select(ech, any_of(mes_molecules)) %>%
  pivot_longer(cols = -ech, names_to = "Variable", values_to = "Valeur") %>%
  group_by(ech, Variable) %>%
  summarise(
    mean = mean(Valeur, na.rm = TRUE),
    sd   = sd(Valeur, na.rm = TRUE),
    min  = min(Valeur, na.rm = TRUE),
    max  = max(Valeur, na.rm = TRUE),
    .groups = "drop"
  )

#export
write_xlsx(pred, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred.xlsx"))
write_xlsx(pred_moy, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred_moy.xlsx"))
write_xlsx(pred_stats, paste0(d0, "vitaspec_R/ROSA_vitaSPEC/predictions/", titre, "_pred_stats.xlsx"))
```

## plot differences sec vs frais
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)


file1 <- readxl::read_excel(paste0(d0,"pred/Pobe_24-25_NIRS_Meso_Frais_pred_moy_out-lier.xlsx"))
file2 <- readxl::read_excel(paste0(d0,"pred/Pobe_24-25_NIRS_Meso_Silica_pred_moy_out-lier.xlsx"))


# file1_clean <- file1 %>%
#   mutate(ech = str_replace(ech, "^[^-]+-([^-]+)-.(.*)$", "\\1-\\2"))
# 
# file2_clean <- file2 %>%
#   mutate(ech = str_replace(ech, "^[^-]+-([^-]+)-.(.*)$", "\\1-\\2"))

file1_clean <- file1 %>%
  mutate(ech = sub("-[^-]+$", "", ech))

file2_clean <- file2 %>%
  mutate(ech = sub("-[^-]+$", "", ech))


df_compare <- inner_join(file1_clean, file2_clean, by = "ech", suffix = c("_frais", "_sec"))


colonnes_communes <- intersect(names(file1), names(file2))
molecules <- setdiff(colonnes_communes, "ech")


pdf("Meso_frais_vs_sec_2024-2025_out-lier.pdf", width = 8, height = 6)

for (mol in molecules) {
  
  col_x <- paste0(mol, "_frais") # abscisse = fichier 1
  col_y <- paste0(mol, "_sec")   # ordonnée = fichier 2
  
  df_plot <- df_compare %>%
    select(x = !!sym(col_x), y = !!sym(col_y)) %>%
    mutate(
        x = as.numeric(gsub(",", ".", x)),
        y = as.numeric(gsub(",", ".", y))) %>%
    drop_na()
  

  if (nrow(df_plot) > 0) {
    
   
    r2 <- summary(lm(y ~ x, data = df_plot))$r.squared
    
   
    p <- ggplot(df_plot, aes(x = x, y = y)) +
      geom_point(shape = 1, alpha = 0.6) +
      
      geom_smooth(method = "lm", color = "blue", se = FALSE, size = 0.5) +
     
      geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
      
      annotate(
        "text",
        x = min(df_plot$x), 
        y = max(df_plot$y), 
        label = paste0("R² = ", round(r2, 3)), 
        hjust = 0, vjust = 1, fontface = "bold", size = 5
      ) +
      
      labs(
        title = paste("Comparaison Frais vs Sec :", mol),
        x = paste(mol, "Prédit sur FRAIS"),
        y = paste(mol, "Prédit sur SEC"),
        caption = "Ligne rouge : y=x"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(face = "bold", size = 14),
        axis.title = element_text(face = "bold")
      )
    
  
    print(p)
  }
}
dev.off()

```

## plot detect outlier
```{r}

library(dplyr)
library(tidyr)
library(ggplot2)
library(tidyverse)
library(tidyverse)


fileHR <- readxl::read_excel(paste0(d0,"vitaspec_R/ROSA_vitaSPEC/predictions/HR_pred.xlsx")) %>% 
  mutate(
    ech = as.factor(as.numeric(str_extract(ech, "(\\d+)(?=_[^_]*$)"))),
    partie_chiffree = str_remove(str_extract(spectrum, "_[0-9]+$"), "_"),
    Repetition = as.factor(case_when(
      nchar(partie_chiffree) <= 2 ~ as.numeric(partie_chiffree),                  
      nchar(partie_chiffree) > 2  ~ as.numeric(str_sub(partie_chiffree, -1, -1))
    ))
  ) %>% 
  select(-c(1), -partie_chiffree)

variables <- unique(fileHR_long$Variable)

liste_ech <- sort(as.numeric(as.character(unique(fileHR_long$ech))))

groupes_ech <- cut(seq_along(liste_ech), breaks = 2, labels = FALSE)

ech_partie1 <- liste_ech[groupes_ech == 1]
ech_partie2 <- liste_ech[groupes_ech == 2]

label_p1 <- paste("Partie 1 (Échantillons", min(ech_partie1), "à", max(ech_partie1), ")")
label_p2 <- paste("Partie 2 (Échantillons", min(ech_partie2), "à", max(ech_partie2), ")")

fileHR_long <- fileHR_long %>%
  mutate(
    ech_num = as.numeric(as.character(ech)),
    partie = case_when(
      ech_num %in% ech_partie1 ~ label_p1,
      ech_num %in% ech_partie2 ~ label_p2
    ),
    partie = factor(partie, levels = c(label_p1, label_p2)) 
  )

nom_fichier_pdf <- "detection_outlier_HR.pdf"

pdf(paste0(d0, nom_fichier_pdf), width = 11.7, height = 8.3)

for (var in variables) {
  
  p <- fileHR_long %>%
    filter(Variable == var) %>%
    
    ggplot(aes(x = ech, y = Valeur, fill = Repetition)) + 
    geom_line(aes(group = ech), color = "black", linewidth = 0.5) +
    geom_point(shape = 21, size = 2, color = "black", alpha = 0.8) +
    facet_wrap(~ partie, scales = "free_x", ncol = 1) + 

    scale_fill_brewer(palette = "Paired") +
    
    labs(
      title = paste("Analyse du composé :", var),
      x = "Échantillons", 
      y = "Valeur prédite",
      fill = "Répétition"
    ) +
    mon_theme
  
  print(p)
}
dev.off()


```
















































